name = "erlvinc"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "erlvinc-db"
database_id = "432a1604-4c10-4c0d-9158-4a9052d29d92"
